#!/usr/bin/env node

var express = require('express'),
    app = express()
    port = process.env.PORT || 3000

app.use(express.static(__dirname + '/example'))
app.use(express.static(__dirname))

app.listen(port, function (err) {
  if (err) console.error(err)
  else console.log('Express listening on http://localhost:'+port+'/')
})

